# SPDX-FileCopyrightText: 2023 Institute for Automation of Complex Power Systems
# SPDX-License-Identifier: Apache-2.0

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TAG: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE: registry.git.rwth-aachen.de/acs/public/villas/signaling

stages:

- test
- packaging
- latest

test:reuse:
  stage: test
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
  - reuse lint

pkg:docker:
  stage: packaging
  image: docker:20.10
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker build --tag ${DOCKER_IMAGE}:${DOCKER_TAG} .
  - docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
  tags:
  - docker
  variables:
    TARGET: app

.latest:docker:latest: &deploy_latest_docker
  stage: latest
  image: docker:20.10
  before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
  - docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
  - docker push ${DOCKER_IMAGE}:latest
  tags:
  - docker

latest:docker:
  <<: *deploy_latest_docker
  only:
  - "/^v\\d+(\\.\\d+)+$/" # Only on version tags

latest:docker:manual:
  <<: *deploy_latest_docker
  when: manual
  except:
  - "/^v\\d+(\\.\\d+)+$/" # Only on version tags
